# Generated by Django 5.0 on 2024-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employer_detailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='accessibility_features',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logo'),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='inclusive_hiring_practices',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry_type',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Banking and Finance', 'Banking and Finance'), ('Biotechnology', 'Biotechnology'), ('Construction', 'Construction'), ('Education', 'Education'), ('Energy', 'Energy'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Information Technology (IT)', 'Information Technology (IT)'), ('Manufacturing', 'Manufacturing'), ('Marketing and Advertising', 'Marketing and Advertising'), ('Media', 'Media'), ('Non-Profit', 'Non-Profit'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Travel and Tourism', 'Travel and Tourism')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='sector',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='support_services',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
