# Generated by Django 5.0 on 2024-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_employer_accessibility_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='accessibility_features',
            field=models.CharField(default='', max_length=500),
        ),
    ]
