# Generated by Django 5.0 on 2024-01-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_alter_employer_accessibility_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='industry_type',
            field=models.CharField(choices=[('All', 'All'), ('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Banking and Finance', 'Banking and Finance'), ('Biotechnology', 'Biotechnology'), ('Construction', 'Construction'), ('Education', 'Education'), ('Energy', 'Energy'), ('Entertainment', 'Entertainment'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Information Technology (IT)', 'Information Technology (IT)'), ('Manufacturing', 'Manufacturing'), ('Marketing and Advertising', 'Marketing and Advertising'), ('Media', 'Media'), ('Non-Profit', 'Non-Profit'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Travel and Tourism', 'Travel and Tourism')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employer',
            name='sector',
            field=models.CharField(choices=[('All', 'All'), ('Private', 'Private'), ('Public', 'Public')], max_length=50),
        ),
    ]
