# Generated by Django 5.0 on 2024-02-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_employer_industry_type_alter_employer_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
