# Generated by Django 5.0 on 2024-02-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_employer_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='bio',
        ),
    ]
