# Generated by Django 4.1.6 on 2023-12-12 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0002_alter_candidate_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=100)),
                ('Organisation', models.CharField(max_length=100)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Current'), (2, 'Previous')], null=True)),
                ('descofjob', models.CharField(max_length=500)),
                ('worked_from', models.DateField()),
                ('worked_till', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
