# Generated by Django 4.1.6 on 2023-12-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(default='skills', max_length=400),
        ),
    ]
