# Generated by Django 4.1.6 on 2023-12-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
    ]
