# Generated by Django 5.0 on 2024-01-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
