# Generated by Django 5.0 on 2024-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateProfile', '0002_personal_details_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
