# Generated by Django 5.0 on 2024-01-06 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateProfile', '0003_alter_personal_details_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institute_city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='institute_country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='institute_state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='result',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='keyAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('proficiency_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Elementary Proficiency'), (2, 'Limited Working Proficiency'), (3, 'Professional Working Proficiency'), (4, 'Full Professional Proficiency'), (5, 'Native / Bilingual Proficiency')], null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Certifications',
        ),
    ]
