# Generated by Django 5.0 on 2024-01-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateProfile', '0004_education_institute_city_education_institute_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institute',
            field=models.CharField(max_length=800),
        ),
    ]
