# Generated by Django 5.0 on 2024-01-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateProfile', '0005_alter_education_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='proficiency_level',
            field=models.CharField(blank=True, choices=[('Elementary Proficiency', 'Elementary Proficiency'), ('Limited Working Proficiency', 'Limited Working Proficiency'), ('Professional Working Proficiency', 'Professional Working Proficiency'), ('Full Professional Proficiency', 'Full Professional Proficiency'), ('Native / Bilingual Proficiency', 'Native / Bilingual Proficiency')], max_length=50, null=True),
        ),
    ]
