# Generated by Django 5.0 on 2024-02-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateProfile', '0006_alter_languages_proficiency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='aadhar_card',
            field=models.ImageField(default='default.jpg', upload_to='candidate/aadharCard'),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='aadhar_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_details',
            name='disability_certificate',
            field=models.ImageField(default='default.jpg', upload_to='candidate/disabilityCertificate'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
