# Generated by Django 5.0 on 2024-02-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateProfile', '0007_personal_details_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_details',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('Blindness', 'Blindness'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Hearing impairment', 'Hearing impairment'), ('Locomotor disability', 'Locomotor disability'), ('Mental illness', 'Mental illness'), ('Haemophilia', 'Haemophilia'), ('Other Disabilities', 'Other Disabilities')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personal_details',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
