# Generated by Django 4.1.6 on 2023-12-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Internship'), (2, 'FULL TIME'), (3, 'HYBRID'), (4, 'REMOTE')], null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(default='role', max_length=200),
        ),
    ]
