# Generated by Django 4.1.6 on 2023-12-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Internship'), (2, 'FULL TIME'), (3, 'HYBRID'), (4, 'REMOTE')], default='Choose Category', null=True),
        ),
    ]
