# Generated by Django 4.1.6 on 2023-12-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, choices=[('Internship', 'Internship'), ('Full Time', 'FULL TIME'), ('Hybrid', 'HYBRID'), ('Remote', 'REMOTE')], default='Choose Category', max_length=100, null=True),
        ),
    ]
