# Generated by Django 5.0 on 2024-01-18 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_lastdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('Australia', 'Australia'), ('Brazil', 'Brazil'), ('Colombia', 'Colombia'), ('Germany', 'Germany'), ('France', 'France')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('Blindness', 'Blindness'), ('Cerebral Palsy', 'Cerebral Palsy'), ('Hearing impairment', 'Hearing impairment'), ('Locomotor disability', 'Locomotor disability'), ('Mental illness', 'Mental illness'), ('Haemophilia', 'Haemophilia')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(blank=True, choices=[(0, 'Entry Level'), (1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (4, '4 Years'), (5, '5+ Years')], null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_qualification',
            field=models.CharField(blank=True, choices=[('10th Pass', '10th Pass'), ('12th Pass', '12th Pass'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
