# Generated by Django 5.0 on 2024-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_job_application_lastdate_job_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Lucknow', 'Lucknow')], default='Choose City', max_length=100, null=True),
        ),
    ]
